name: .NET to NuGet

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Replace with your .NET version

    - name: Restore dependencies
      run: dotnet restore ./Promact.Caching/Promact.Caching.sln

    - name: Build
      run: dotnet build ./Promact.Caching/Promact.Caching/Promact.Caching.csproj --no-restore --configuration Release

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: 7

    - name: Test
      run: dotnet test ./Promact.Caching/Promact.Caching.Test/Promact.Caching.Test.csproj

    - name: Pack
      run: dotnet pack ./Promact.Caching/Promact.Caching/Promact.Caching.csproj --no-build --output nupkg

    - name: Push to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_PUBLISH_API }} --source https://api.nuget.org/v3/index.json
